### ISSUE TITLE
[FEATURE] Design changes to alert emails

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1512]
### **Who requested this feature?**
@gal-agmon 

### **What needs to be done**
- [x] Set a max height for the header logos
- [x] Use consistent font size, alignments, and button styles
- [x] Replace the MailChimp footer with our custom footer
- [x] Display the timezone without underscore characters
- [x] Reduce gap between **warning** and **expected exposed** as per design
- [ ] Increase darkness/contrast of text colour in Chrome
- [x] Sort events by time then by severity (trigger and warning for the same time should list the trigger first)
- [ ] Flash flood
    - [ ] Replace N-month with the name of the month in event name
    - [x] Show "ongoing" instead of "0 months from now"
    - [x] show exposed population for warning
- [x] Typhoon
    - [x] Round the % value to 2 decimal places
    - [x] show % of houses affected for warning

### **Acceptance Criteria**
- [x] Create emails with these changes implemented
- [x] Capture screenshots and save raw `.eml` files
- [x] Get approval from design

### **Links**
[For screenshots and context.](https://dev.azure.com/redcrossnl/IBF%20System/_workitems/edit/26750)

**Comment by gulfaraz** [comment]
@gal-agmon the updated emails [are here](https://rodekruis.sharepoint.com/sites/510-CRAVK-510/Gedeelde%20%20documenten/%5BRD%5D%20IBF%20portal/[ibf-emails](https://rodekruis.sharepoint.com/sites/510-CRAVK-510/Gedeelde%20%20documenten/%5BRD%5D%20IBF%20portal/ibf-emails?csf=1&web=1&e=SZWrmH)?csf=1&web=1&e=SZWrmH) for your review

**Comment by gal-agmon** [comment]
@gulfaraz  the links shows a 404

**Comment by gal-agmon** [comment]
> The N-month text is an event name and is implemented such that cannot be edited. To fix this is a separate much larger effort. If you find it critical, create another issue with the required details.
Let's make it a separate task to pick up later

**Comment by gulfaraz** [comment]
@gal-agmon fixed the link, try again

**Comment by gulfaraz** [comment]
@gal-agmon fixed the link, try again

**Comment by gal-agmon** [comment]
As I mentioned on Teams the low warning text color should be dark yellow #665606
<img width="639" alt="image" src="https://github.com/user-attachments/assets/1803b64b-e5c3-41cc-b4d5-3a517eafac3d">

**Comment by gal-agmon** [comment]
@gulfaraz is the warning data on a separate task?

**Comment by gal-agmon** [comment]
Can we add 10px padding around each logo 
<img width="309" alt="image" src="https://github.com/user-attachments/assets/e265a15f-1450-4bce-b43b-0388c20ad6e8">
<img width="418" alt="image" src="https://github.com/user-attachments/assets/a64d43e5-6bd0-48a9-a17a-bff76ef32bdb">

**Comment by gulfaraz** [comment]
@gal-agmon [here are the updated emails](https://rodekruis.sharepoint.com/sites/510-CRAVK-510/Gedeelde%20%20documenten/%5BRD%5D%20IBF%20portal/ibf-emails/review-1?csf=1&web=1&e=ziI1Lx). good review.

The padding is out of scope for this issue. But, I want to fix it so I created #1533

**Comment by gal-agmon** [comment]
@gulfaraz we should not show TA that are exposed on 0 that is also a ticket for Malawi Flash Floods  
<img width="622" alt="image" src="https://github.com/user-attachments/assets/18c83da9-2cb9-4eed-9e19-310270a90f2b">
The note regarding no info for warning should not be there if we have info :)
<img width="657" alt="image" src="https://github.com/user-attachments/assets/49729a08-df81-40cf-807d-618e8219e634">
it should be the same as the trigger

**Comment by gulfaraz** [comment]
@gal-agmon [here you go](https://rodekruis.sharepoint.com/sites/510-CRAVK-510/Gedeelde%20%20documenten/%5BRD%5D%20IBF%20portal/ibf-emails/review-2)

**Comment by gal-agmon** [comment]
@gulfaraz It should be exactly the same text if we have info for trigger and warning. "Expected exposed traditional authorities in order of exposed population:"

**Comment by gulfaraz** [comment]
The code explicitly hid "in order of exposed population" for warning alerts. It was implemented as such to meet the [design requirement](https://www.figma.com/design/sfszsq2Jxp9Ep979zGL2Zi/%F0%9F%8C%8A-%F0%9F%87%BA%F0%9F%87%AC-IBF-Uganda-floods?node-id=6890-25136&t=guzR2swEPpNB1DEi-1).

![Screenshot 2024-07-30 at 17 01 18](https://github.com/user-attachments/assets/67ae3594-bcc9-4397-a9e0-f7a2ffc6813b)

I've updated the text as per your comment. [Here is the email](https://rodekruis.sharepoint.com/sites/510-CRAVK-510/Gedeelde%20%20documenten/%5BRD%5D%20IBF%20portal/ibf-emails/review-3?csf=1&web=1&e=qxh3Fm).

**Comment by gulfaraz** [comment]
@gal-agmon No worries. It's good that you caught this before we released it.

Is there any other design feedback related to multi-level alert emails?

**Comment by gal-agmon** [comment]
All looks great except the text in the beginning:
<img width="363" alt="image" src="https://github.com/user-attachments/assets/0654e1e0-2800-470c-9904-e35bdd91479d">
not sure what happened to the font style and gaps :/

**Comment by gulfaraz** [comment]
@gal-agmon That is _hidden_ metadata used by the email client. Does it appear in your email app or browser? `.eml` files should be viewed in an email client. Not in a file viewer or browser which display these raw email headers.

**Comment by gal-agmon** [comment]
I guess we are done ✅ ⭐️
