### ISSUE TITLE
[Task] Switch to mjml to handle email templates

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1515]
### **Who requested this feature?**
@gulfaraz 

### **User Story**
As a developer
I want to use mjml to create email templates
So that emails are easier to create and style

### **What needs to be done**
- Install mjml
- Migrate to object structure
- Test for multiple disasters

### After first review with @gulfaraz 
- [x] Fix width on mobile
- [x] Set Arial as font
- [x] Add margin between action button and description on mobile
- [x] Fix "from nows from now" typo
- [x] Use correct button labels
- [x] Add Mailchimp footer
- [x] Fix event trigger issued text's size and spacing
- [ ] Use `date-fns` instead of `moment`
- [ ] (optional) Fix rounded buttons on Outlook (Windows)
- [ ] Make single-logo countries logos smaller (by limiting height and adjusting width to that?)

**Comment by jannisvisser** [comment]
@arsforza @gulfaraz 
- I have merged the fix.email-logos branch into this one as discussed yesterday.
- I noticed that the single logo countries have a huge logo, but that was already the case before, so decided to not let it block the email logo item, but maybe good to fix in this item still? (made a task above for  it)
![Image](https://github.com/user-attachments/assets/7fc93941-58fa-4a0d-bf0c-32f03d7f560b)

**Comment by gulfaraz** [comment]
> I noticed that the single logo countries have a huge logo, but that was already the case before, so decided to not let it block the email logo item, but maybe good to fix in this item still? (made a task above for it)

You should use `height: 50px` in the [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/height) or image `height="50"` in the [IMG](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/height) tag to set the height of the logo.

**Comment by gulfaraz** [comment]
The can be closed after merging PRs #1527 and #1594.
