### ISSUE TITLE
[Task] Create monitoring dashboard

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1520]
### **User Story**
Create a monitoring report for the production environment that daily updates for all country-disasters:
- trigger status
- last update date

```[tasklist]
### **What needs to be done**
- [x] create dashboard page
- [x] create link to dashboard page in dev menu
- [x] add andrea's html in dashboard page
- [x] fill page dynamically (on load, not via cronjob)
- [x] ask andrea to keep sending manual report weekly until this is released
- [x] make disaster-type logo's non-triggered/triggered dynamic
- [x] make danger status dynamic
- [x] remove country-name from status page (and activation log page where relevant?)
- [x] code review (subscriptions/types/angular setup/duplication of code with other services?/etc)
- [x] review styling
- [x] error handling on missing date or other data
- [x] add hours because of 6-hourly pipelines (flash-floods/typhoon)
```

**Comment by jannisvisser** [comment]
@gulfaraz is [this](https://portal.azure.com/#@rodekruis.onmicrosoft.com/dashboard/arm/subscriptions/b2d243bd-7fab-4a8a-8261-a725ee0e3b47/resourcegroups/510global-ibf-system/providers/microsoft.portal/dashboards/ad38f173-db8d-46af-a97d-46d473a960f8) the dashboard page we would want to add this to?

**Comment by jannisvisser** [comment]
Updated task list after discussion with @gulfaraz

**Comment by jannisvisser** [comment]
Asked @gulfaraz for code review (see task list on top)
