### ISSUE TITLE
[Design] Use consistent height, width, padding in the logos used in email alerts

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1533]
### **Who made this request for Design support?**
@gulfaraz from #1512 

### **What type of request?**
UI Design

### **What is requested?**
Images used in the email alerts have inconsistent spacing.

### **What needs to be done**
- [x] Decide on a fixed height and width
- [ ] Modify the images to fit the decided height and width
- [x] Modify the images to have sufficient spacing

### **Acceptance Criteria**
- [ ] Outcome(s) reviewed
- [ ] Documented the outcome(s) in the appropriate location
- [ ] Handed over to requester
- [ ] Codesign sessions logged in 510EspoCRM

### **Additional context**
We use these images in the emails with a certain margin applied. Because some images have whitespace in the image the additional padding imposed by the code becomes excess. The other way is if we remove the padding imposed by the code, the images appear to have insufficient whitespace.

Links to the images,
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/c44cb471-0595-454d-aad6-d1050553315f.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/af6240bf-bdd3-9982-9ca5-44f7e5a71f01.jpg
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/35e3a47b-65d0-9b15-ad8f-ac19300ef5b6.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/905748b3-7aaf-4b5e-b5b9-516ad6f4105a.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/eedbd97e-52c1-4a16-8155-9b607ad05ad2.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/6907dc6e-311a-402b-b97d-551f04ef3d0b.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/ff56e5b1-f3be-1d68-be49-7898ba16be81.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/575cc45e-7050-4b2d-d8bc-d1f278e42a66.png
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/ee9473a2-cac5-aec2-a2ee-cee872837098.jpeg
https://mcusercontent.com/e71f3b134823403aa6fe0c6dc/images/093cd804-0be0-21f3-c712-f210dd0f7c05.png

**Comment by talrosenthal** [comment]
![Image](https://github.com/user-attachments/assets/c8eae678-fe24-4ebd-990e-3ab8f3e22565)
![Image](https://github.com/user-attachments/assets/f44b97d7-3529-44c9-8f6b-5cc2c5b5b922)
![Image](https://github.com/user-attachments/assets/2779e2d2-b473-4a4a-97b4-4a50b939b261)
![Image](https://github.com/user-attachments/assets/7bff4ed7-7146-4c46-a014-55dcf4d66e0d)
![Image](https://github.com/user-attachments/assets/b4eafa0c-c9ca-4a1f-882a-dca7fcf01b18)
![Image](https://github.com/user-attachments/assets/418b4c24-4d99-4373-ba07-202e9d292121)
![Image](https://github.com/user-attachments/assets/c4647c71-8950-47e9-ad37-c22d66fc3759)
![Image](https://github.com/user-attachments/assets/04921b55-63f1-4f1c-8ef0-1870c266726d)
![Image](https://github.com/user-attachments/assets/78ebc057-868d-43da-b7a7-b39c70478002)

**Comment by jannisvisser** [comment]
After feedback from @gulfaraz I reversed this on production.
- uploaded old logo's again mailchimp (also left new logo's)
- updated production with the URLs of these (newly added) old logo's
- I kept the repository (and therefore test and demo once released) on the new logo URLs.
- I made a note in #1555 to make sure we remember to update again once we release.
