### ISSUE TITLE
[BUG] "About Trigger" redirects to expired link

### ISSUE THREAD

**Issue by tenda1-wbm** [rodekruis/IBF-system#1543]
### **Who notified us about the bug?**
<a href="https://github.com/tenda1-wbm">Tendai Mbwanda</a>

### **Describe the bug**
When viewing the platform during a triggered drought, the "About Trigger" button redirects to a page that says the link has expired.

### **To Reproduce**
1. Ensure you are viewing the platform in drought mode during a drought trigger.
2. Click on 'About Trigger'.
4. See response message.

### **Expected behavior**
The link should lead to a document describing the triggered drought.

### **Screenshots**
![image](https://github.com/user-attachments/assets/242d8106-0183-428a-8b4d-507feed3ac93)

### **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 128.0.3 (64-bit)

**Comment by gulfaraz** [comment]
@tenda1-wbm may I know the country names and hazard types for which the link does not work?

**Comment by tenda1-wbm** [comment]
country name: Uganda
hazard type: Drought

for the other 2 hazard types, the redirection sent me to a page which stated that i was not allowed access to a google document. I imagine this is the intended behaviour which is why i only flagged the expired link.
@gulfaraz

**Comment by jannisvisser** [comment]
This is already part of [issue 838](https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=79112675&issue=rodekruis%7CAnticipatory-Action%7C838)
