### ISSUE TITLE
Release multi threshold (pipeline & code)

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1555]
Prerequisites
- Gulfaraz will fix compact number issue on percentages (typhoon)

```[tasklist]
### Other release notes to watch out for
- [x] update trigger statements all countries
- [x] Test migration on production data
- [x] Create release and check ibf-demo
- [x] Deploy to prod (check .env/raster-files/npm packages (mjml))
- [x] Update seed data via API-calls
- [x] Switch off malaria/dengue
- [x] Start first manual pipeline run on production (check raster file writing permissions)
- [x] Also update: email logo URLs on prod API (+ remove old logo's from mailchimp) see task 1533
- [x] Send out communication
- [x] Check and remove bug #1649 + other similar
- [x] Update what's new in IBF
- [x] Create follow-up release
- [ ] Monitor first automated pipeline run on production (next day)
```

**Comment by diderikvw** [comment]
Refinement:
1. Prerequisite: some test item.
2. Deploy pipeline and code at same time.
3. Code deployment: also add data via API on production.
4. Out of scope for this item: version nrs code and pipelines? Leave it for this item. Phuoc will get an idea on how to approach this separately. Jannis knows about a prior Spike in DevOps. With Bouke and Aki as well.

**Comment by diderikvw** [comment]
Memory will give a training 4 to 7 November, so needs to at least be able to demo the new release then.

**Comment by jannisvisser** [comment]
@p-phung I've made a task in this item to create the trigger statements for all countries. Can you provide them with help of @jmargutt  (technical phrasing) + @gal-agmon (UX copy)?

**Comment by p-phung** [comment]
@gal-agmon @jannisvisser where can I find all the trigger statements for riverine floods?

**Comment by jannisvisser** [comment]
@p-phung https://github.com/rodekruis/IBF-system/blob/master/services/API-service/src/scripts/json/notification-info.json

**Comment by gal-agmon** [comment]
> [@p-phung](https://github.com/p-phung) I've made a task in this item to create the trigger statements for all countries. Can you provide them with help of [@jmargutt](https://github.com/jmargutt) (technical phrasing) + [@gal-agmon](https://github.com/gal-agmon) (UX copy)?

@p-phung can we have a shared place to review all statements?
