### ISSUE TITLE
Add Aderajew.admassu@redcrosseth.org to IBF

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1569]
**Who requested this task?**
@aklilu [here](https://teams.microsoft.com/l/message/19:meeting_NmQyYTE5MGItYjc0OS00MTZkLWFjOGItMjYyYmYyZTVhZGNj@thread.v2/1725883985366?context=%7B%22contextType%22%3A%22chat%22%7D)

**What needs to be done**

- [x]  ~~Create IBF user~~ User already in IBF-portal, password reset
- [x]  Add email to Mailchimp
- [x]  Send welcome email

**Acceptance Criteria**
 Requester follows up with new user to confirm access

**Details of the new user:** 
Email: Aderajew.admassu@redcrosseth.org
first Name : Aderajew
middle Name : NA
last Name: Admassu

**Comment by gulfaraz** [comment]
@arsforza close the issue when you move it done
