### ISSUE TITLE
[BUG]  chat bubble 3 time the same

### ISSUE THREAD

**Issue by gal-agmon** [rodekruis/IBF-system#1575]
### **Who notified us about the bug?**
@gal-agmon 
### **Describe the bug**
when I am looking at a municipality in the Philippines (lowest admin area) I see the same chat bubble 3 time

Production:
![image](https://github.com/user-attachments/assets/938a83dd-e3d2-49be-8799-eccbbad6f013)

Demo:
![image](https://github.com/user-attachments/assets/4df94e9a-e7ad-45d4-9895-5cd5c7c66b85)

### **To Reproduce**
1. Go to 'philippine flodd'
2. Click on 'province' -' municipality' 
4. See the same chat bubble 3 time

**Comment by jannisvisser** [comment]
@gulfaraz I'm pretty sure this is a symptom if the bug that we recently solved already? If so, @gal-agmon this should already be fixed on ibf-test, not on ibf-demo yet.

**Comment by gal-agmon** [comment]
@jannisvisser  this is test
<img width="721" alt="image" src="https://github.com/user-attachments/assets/f464ff32-6e5c-4eec-832b-85d2a6130368">

**Comment by jannisvisser** [comment]
Ok, clear @gal-agmon, let's tag @BlaiseSelvan then to prioritize.

**Comment by jannisvisser** [comment]
reproduced locally (with 2 speech bubbles, not 3)
![Image](https://github.com/user-attachments/assets/089a4ed4-c17a-4ada-9707-f2381a86aa22)
