### ISSUE TITLE
[TASK] Setup playwright for e2e tests

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1581]
### **Who is your contact person for this task?**
@gulfaraz 

### **User Story**
As a dev
I want to run e2e tests
So that I don't break existing functionality

```[tasklist]
### **What needs to be done**
- [x] Remove Cypress / lighthouse
- [x] Install Playwright
- [x] Write a test test
- [x] resolve final PR comments + add readme
- [x] Update testing-related documentation (if any)
- [x] remove current cypress badge
- [x] Update CI/CD to run playwright
- [x] Update main README
- [x] e2e test call api endpoins instead of using api test helper me (made separate task)
- [x] merge the workflows
- [ ] check deploy to ibf-test with new env + set on ibf-demo/prod
```

```[tasklist]
### **Acceptance Criteria**
- [ ] Reviewed by the other devs
- [ ] Demo to the team at sprint review
```

### **Additional context**
[![IBF-system](https://img.shields.io/endpoint?url=https://dashboard.cypress.io/badge/detailed/jkaw7k/master&style=flat&logo=cypress)](https://dashboard.cypress.io/projects/jkaw7k/runs)

**Comment by jannisvisser** [comment]
@gulfaraz @arsforza this item is done and reviewd back and forth between @Piotrk39 and me. The PR is merged. But putting the item here on review for both of you, so you can have a look (see acceptance criteria on this).

**Comment by jannisvisser** [comment]
@gulfaraz will include in his work to have the e2e test call API endpoints instead of using API-test helper methods.

**Comment by gulfaraz** [comment]
@jannisvisser and @Piotrk39 I've updated the main CI workflow to include e2e and integration tests. Like all things IBF, it wasn't a clean change to get them working. You can see the PR notes for details. Please review #1598 when you have the time. Thanks!
