### ISSUE TITLE
[TASK] Setup test plan tool for GitHub

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1582]
### **Who is your contact person for this task?**
@gulfaraz 

### **User Story**
As a tester
I want to use a test plan
So that I can track the test results

```[tasklist]
### **What needs to be done**
- [x] Find a test plan tool
- [x] Add example test suite
- [x] Add Test Plan collaborators to the tool
- [x] Add integration between the tool and "IBF-System" github repository
- [x] Discuss pricing
```

```[tasklist]
### **Acceptance Criteria**
- [x] Tested and reviewed
- [ ] Demo to the team at sprint review
```

### **Additional context**
I don't know what this is. I'm going by what Piotr said at the kick-off and a quick google search.

**Comment by Piotrk39** [comment]
There are two main ways that in my opinion we should approach this:

- Transparency & collaboration
  - Responsible team members should either view/ write/ edit test cases in the tool
- Level of integration with Github
  - Ideally each feature should be tested by a set of tests that are easily accessible from issue level.

There are two main options that I can see at this moment:
- **"Azure Test Plan"** that is already set up also for "121 - Platform" and can be reused in GitHub. The only downside is that most probably we have to add another 2 subscriptions since from what I've seen so far there is no "Tested by" option in GitHub tasks and integration seems to be limited.
- **"TesMo"** that has GitHub integration out of the box is easy to use and has nice clear UI. It's basic subscription covers up to 10 team members.

If we would like to continue with this I'd like to prepare a demo for both tools and also install TestMo in our repository to test the usability of the tool.

**Comment by gulfaraz** [comment]
@BlaiseSelvan As the Azure integration is limited, would it be possible to get a [TestMo Team plan](https://www.testmo.com/pricing)?

From my discussion with @Piotrk39, it comes with all the features we need for IBF QA.

**Comment by Piotrk39** [comment]
@gulfaraz there is 20 day trial for TestMo so for a demo we are covered.

**Comment by gulfaraz** [comment]
@Piotrk39 Can you check if [Qase](https://qase.io/pricing) meets our Test Plan needs? They have a free plan for small teams.

**Comment by Piotrk39** [comment]
Summary:

1. As it goes with integration of Qase to our repository there is a bug from Qase's side and it simply cannot connect to IBF-system repository. It would require lengthy debug with Jacopo and I just believe it is not worth the time fixing it each time there is an issue and depending on someone outside of development team to fix it with.
2. Playwright reporter is much easier to configure but again it requires complicated setup and only QA maybe can benefit from it.
3. As a storage for Test suites and test cases it is brilliant. It has simple and readable UI that makes writing tests a blissful experience. Tests can be assigned into test suites so depending on the needs specific configurations can be assigned. e.g Regression testing or Smoke testing suites.

It is a decent Test management tool that for most part is for free and can scale up or down depending on the team's testing needs.

**Comment by gulfaraz** [comment]
I have installed GitHub on Qase and Qase on GitHub. Let me know if you're still blocked.

> As it goes with integration of Qase to our repository there is a bug from Qase's side and it simply cannot connect to IBF-system repository. It would require lengthy debug with Jacopo and I just believe it is not worth the time fixing it each time there is an issue and depending on someone outside of development team to fix it with.

![Image](https://github.com/user-attachments/assets/7e3e3320-b727-44a5-a158-1fd0bfe405ce)
![Image](https://github.com/user-attachments/assets/6dc29dbd-51bd-4f9b-b535-d62467d90e74)

**Comment by Piotrk39** [comment]
I have setup the test suites and added reporter in this task: https://github.com/orgs/rodekruis/projects/23/views/29?pane=issue&itemId=82770707&issue=rodekruis%7CIBF-system%7C1644

The way we would like to use it we can discuss in the future.

**Comment by gulfaraz** [comment]
Nice! It comes with screenshots and videos too. Good work @Piotrk39 !

![Image](https://github.com/user-attachments/assets/69f272ee-9151-4794-8221-9d73c2ab1e78)
![Image](https://github.com/user-attachments/assets/fe245b2a-6116-453e-a75a-e4d00e4ce1fb)

**Comment by Piotrk39** [comment]
Just a small annotation about pricing. For all 3rd party integrations to work paid plan is required after the trial month: https://qase.io/pricing

**Comment by gulfaraz** [comment]
> Just a small annotation about pricing. For all 3rd party integrations to work paid plan is required after the trial month: https://qase.io/pricing

Will the integrations work on the Free plan?

**Comment by Piotrk39** [comment]
Unfortunately Qase support informed me that integrations will only be available till end of the month with free version.

**Comment by gulfaraz** [comment]
Thank you for the confirmation @Piotrk39
