### ISSUE TITLE
[TASK] Update the architecture diagram

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1584]
### **Who is your contact person for this task?**
@gulfaraz 

### **User Story**
As an external dev
I want to understand the IBF system
So that I can use IBF locally

```[tasklist]
### **What needs to be done**
- [x] Create an architecture diagram for IBF
- [x] Remove old architecture diagram from README, wiki, docs
- [x] Add new architecture diagram to wiki
```

```[tasklist]
### **Acceptance Criteria**
- [x] Reviewed by other devs
- [x] Update the wiki with explanation of the diagram
```

### **Additional context**
[Current architecture diagram](https://github.com/rodekruis/IBF-system?tab=readme-ov-file#system-design)

[Why you need an Architecture Diagram?](https://www.youtube.com/watch?v=ek8ArrOfJxA)

**Comment by diderikvw** [comment]
Hi @gulfaraz , I had a look at the architecture diagram. I understand the gist of it, and have some suggestions:
1. Use the high-level "IBF System" diagram we created together last week and shared in Teams as "starting point", so how the product is defined in there is recognizable here as well. As components and names.
2. Be clear of the "visual language" that you use. What is a circle? What is a rectangle? I suggest to use UML, as that is a clearly defined and simple visual language. In this case: a UML Component Diagram as Structural Diagram would fit, I think.
3. Additional to a more conceptual diagram, consider something like a UML Deployment Diagram as well. So the Azure infrastructural architecture is also visualized and can be easily digested (not all Azure resources in detail, but high-level). I can point to an example for 121. Note that we do not put this on an open GH repo, as our Azure config is somewhat secret, no need to share that publicly, also a security risk.
4. For the Pipelines, make it more explicit of the actual pipelines we have. I am not sure if this needs to be reflected then in both diagrams. Perhaps that is overkill.
5. What does the circle "Trigger Model" mean practically? Is that e.g. en App Service running code from GH that is used to create forecasts for all data sources?
6. Nice to use mermaid, is it possible to do something with the buttons? As now they overlay part of the diagram: 
7. ![Image](https://github.com/user-attachments/assets/70a496bc-d819-49e8-904a-999731e362b6)

**Comment by gulfaraz** [comment]
> I understand the gist of it

Thank you for the compliment.

> Use the high-level "IBF System" diagram we created together last week and shared in Teams as "starting point", so how the product is defined in there is recognizable here as well. As components and names.

This is not possible in the architecture diagram. The high-level **IBF System** diagram from last week is _conceptual_. It does not reflect the underlying software architecture. We have a [Glossary](https://github.com/rodekruis/IBF-system/wiki/Glossary) to supplement IBF documentation to address this discrepancy.

> On 2, 3, and 4.

I used generic symbols where possible but I understand it's not clear. I have not used UML and C4 but feel free to pick it up and improve on the existing diagram.

> On 5 and 6.

I did my best to capture the outline of the pipeline. I don't understand the details of the pipeline like what is a **trigger model**. I don't know which pipelines are in production. If you need additional details, feel free to update the diagram.

> Nice to use mermaid, is it possible to do something with the buttons? As now they overlay part of the diagram

Not that I know of.

----
I'm aware there are many possible improvements. This issue was created because the [old diagram](https://github.com/rodekruis/IBF-system/blob/096e7d9e0ce6f40e3679ce766a5923a5b8ac73e2/system-design/ibf-system-design.PNG) needed an update.

:pray: I appreciate your time and effort to review this work.

**Comment by gulfaraz** [comment]
@jannisvisser reviewed the software architecture diagram in a call. We agree that @diderikvw's suggestions are valid but do not fit in the allocated timebox.

We concluded that the current diagram is sufficient for this task. Feel free to create follow-up tasks for further improvements.

**Comment by p-phung** [comment]
@diderikvw can we schedule something in the week of 11 November?

**Comment by diderikvw** [comment]
Yes, I will close this item and create a Spike for the 101 session.
