### ISSUE TITLE
Create issues for E2E tests in trigger scenarios

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1599]
### **Who requested this task?**
@gulfaraz 

### **What needs to be done**
- [x] Identify differences between trigger and no-trigger state on the UI (start with Uganda flood)
- [x] Update test plan
- [x] Create follow-up items

### **Acceptance Criteria**
- [x] Follow-up items created

### **Relevant links**
Use [prioritization](https://github.com/rodekruis/IBF-system/issues/1592#issuecomment-2371321412) done for the no-trigger state for reference.

**Comment by Piotrk39** [comment]
All the above test were added in "Qase" as test scenarios and separate items were created in "New" tab
