### ISSUE TITLE
Apply existing e2e tests to other countries and hazards

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1601]
### **Who is your contact person for this task?**
@gulfaraz 

Apply the e2e tests written for Uganda floods trigger and no-trigger states to other countries and hazards.

```[tasklist]
### **What needs to be done**
- [ ] Run the no-trigger e2e tests for Zambia, Malawi, South Sudan, Ethiopia, Kenya, Philippines
- [ ] Run the trigger e2e tests for Zambia, Malawi, South Sudan, Ethiopia, Kenya, Philippines
```

```[tasklist]
### **Acceptance Criteria**
- [ ] Report results in a comment on this issue.
```

### **Additional context**
The behaviour should be the same across countries and all the tests pass. Then we can move on to other hazards and scenarios.

However, if there are discrepancies and exceptions, then create spikes or bugs to address these discrepancies.

**Comment by Piotrk39** [comment]
Moved to Dev Ops
