### ISSUE TITLE
Add 3 integration tests for user module

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1613]
### **Who is your contact person for this task?**
@gulfaraz

```[tasklist]
### **What needs to be done**
- [x] Choose 1 or more critical API endpoint(s) in the [user](https://github.com/rodekruis/IBF-system/tree/5bb38d45f41e84c4e890b04315f7593b8bdb8be7/services/API-service/src/api/user) module
- [x] Identify 3 tests to write for the identified endpoint(s)
- [x] Add the tests in the [integration tests folder](https://github.com/rodekruis/IBF-system/tree/5bb38d45f41e84c4e890b04315f7593b8bdb8be7/services/API-service/test)
```

```[tasklist]
### **Acceptance Criteria**
- [ ] Integration tests are in the repo
- [ ] CI passes with the new tests
```

### **Additional context**
- This issue is a follow-up from https://github.com/rodekruis/IBF-system/issues/1583
- [How to write a good test?](https://stackoverflow.com/a/3258768/1753041)

**Comment by jannisvisser** [comment]
@arsforza makes sense if you review this, also in relation to the unit test item you are working on. Makes sense if we discuss that item tomorrow, as it doesn't necessarily make sense to test the exact same things. So let's discuss what makes sense to unit test still, given these api tests.
