### ISSUE TITLE
Update MWI mock with data used for demo

### ISSUE THREAD

**Issue by arsforza** [rodekruis/IBF-system#1629]
Follow up from [#743](https://github.com/rodekruis/Anticipatory-Action/issues/743)

- [ ] Use the data below to either:
  - Update the triggered scenario already present
  - Create a second triggered scenario

[mwi-flash_floods-demo.zip](https://github.com/user-attachments/files/17289532/mwi-flash_floods-demo.zip)

**Comment by arsforza** [comment]
Closing because changes will be done in [#743](https://github.com/rodekruis/Anticipatory-Action/issues/743)

**Comment by Memory1997** [comment]
@arsforza just checking on this issue. If it has been addressed elsewhere, you can guide me to the resolution . A more realistic demo has been done for the training in Malawi, do we also have a mock scenario that can be used for a simulation. So to send out a "fake" trigger during the training as part of a simulation exercise. Not sure how this can be done?

**Comment by gulfaraz** [comment]
@Memory1997 Mock data has been updated in #743 and https://github.com/rodekruis/IBF-system/pull/1635.

You can view the updated mock scenario in [ibf-demo](https://ibf-demo.510.global).

**Comment by Memory1997** [comment]
Thanks @gulfaraz . Is it possible that during the training (so on the 07th Nov), the users can receive a notification on their Whataspp showing a trigger based on the mock data?

**Comment by Memory1997** [comment]
Understood. I will create an issue for this.
