### ISSUE TITLE
Add E2E test for: "Aggregates title should be dynamic"

### ISSUE THREAD

**Issue by Piotrk39** [rodekruis/IBF-system#1641]
```[tasklist]
### Tasks
- [x] Add E2E automation script
- [x] Refactor imports and dependencies
```

**Comment by Piotrk39** [comment]
Test case description: https://app.qase.io/project/IBF?suite=7&previewMode=side&case=12

**Comment by gulfaraz** [comment]
> Should the test be skipped since there is pre-existing bug?

Yes, good idea @Piotrk39. I've [updated](https://github.com/rodekruis/IBF-system/issues/1657#issue-2588594691) https://github.com/rodekruis/IBF-system/issues/1657 to unskip this test when the bug is fixed.
