### ISSUE TITLE
[BUG] Lead time is highlighted in no-trigger state

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1649]
### **Who notified us about the bug?**
@LarsRedCross via [Teams](https://teams.microsoft.com/l/message/19:b262590b1cc34ade9bbdb584f0765b31@thread.skype/1728647983653?tenantId=d3ab9790-6ae2-4bd8-aa5e-02864483e7c7&groupId=48e3c654-ac7d-4abc-9c70-ad637fb0a85f&parentMessageId=1728646296848&teamName=510%20-%20Anticipatory%20Action&channelName=%5BRD%5D%20IBF%20system&createdTime=1728647983653)

### **Describe the bug**
The lead time is highlighted in the no-trigger state for PHL flood. This occurs in [v0.261.5](https://github.com/rodekruis/IBF-system/releases/tag/v0.261.5) on production.

### **Expected behavior**
No lead time should be highlighted in no-trigger state.

### **Screenshots**
![Image](https://github.com/user-attachments/assets/6bb96040-efb8-49ca-932d-453d47f1f02f)

**Comment by jannisvisser** [comment]
@gulfaraz when I load 'no-trigger' on ibf-demo, it loads correctly. So let's wait if this still appears after the release?
![Image](https://github.com/user-attachments/assets/43ad93ed-890b-4c52-85a4-fcc1d53bf990)

**Comment by jannisvisser** [comment]
@LarsRedCross @gulfaraz the release is done now and I cannot specifically check this for PHL floods no-trigger, as it's now triggered. But for other countries no-trigger I don't see this behavior, so I consider this solved. If it' seen again it can be re-reported.
