### ISSUE TITLE
Explain Lars about Alert log feature 

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1650]
### **Who requested this spike**
@LarsRedCross 

### **Functional or Technical Spike**
The alert log shows a row per admin level. This appears to work in other countries but not for Philippines. See the screenshot below.
This was observed in [v0.261.5](https://github.com/rodekruis/IBF-system/releases/tag/v0.261.5) on prod.

### **User Story**
As a disaster manager
I want to know historical alerts
So that I can learn and plan from past hazards.

### **Acceptance Criteria**
- [ ] Document decision with the team
- [ ] Create follow up issues if needed

### **Screenshots**
![Image](https://github.com/user-attachments/assets/eb5751e0-6d8d-426c-abe0-5ac277ed2a7a)

**Comment by jannisvisser** [comment]
Conclusion
- We will not pick this up, as it is feature improvement, which is not a priority now.
- @BlaiseSelvan will inform Lars, including explnation of what the feature currently does, (and asks dev for help beforehand if needed).

**Comment by LarsRedCross** [comment]
Understood :)
