### ISSUE TITLE
0 year return period on SSD GloFAS station

### ISSUE THREAD

**Issue by gulfaraz** [rodekruis/IBF-system#1798]
### **Who notified us about the bug?**
Question from @a-marije-j on [IBF Team Chat](https://teams.microsoft.com/l/message/19:fae59693d3cf4aceb949d0be06c22865@thread.v2/1732172182317?context=%7B%22contextType%22%3A%22chat%22%7D)

### **Describe the bug**
There is confusion about the return period in the screenshot,

![Image](https://github.com/user-attachments/assets/72a0f434-0bc9-4a60-a492-08a753557686)

Clarification from @jmargutt is,
> the forecasted river discharge corresponds to a return period of 0 years, that is correct. There is no flood. If it would be 5 years, that would mean that there is a flood, 5-year-return-period-bad flood.

@gal-agmon informed that in the case of 0 year return period, we should not show the text in parentheses.
> (Corresponding to a return period of 0 years)

### **To Reproduce**
1. Go to SSD floods non-trigger
2. Click on GloFAS station
3. See 0 year return text

### **Expected behavior**
Do not show return period text when there is no warning or trigger.

**Comment by jannisvisser** [comment]
@gulfaraz I would say to put bugs immediately on 'refine' and on a refinable position. As discussing them (even shortly) in refinement is our immediately our best way of determining urgency together (with possible result also to move it down again). FYI @BlaiseSelvan @diderikvw

**Comment by jannisvisser** [comment]
I picked this up in the sprint because I had some time to spare for something small.
