### ISSUE TITLE
Docker-compose does not activates all the containers

### ISSUE THREAD

**Issue by SwatiTh** [rodekruis/IBF-system#826]
**Description**

Upon running the <docker-compose -f docker-compose.yml -f docker-compose.override.yml up> all the containers are not started mentioned in the docker-compose file. Some containers throw certain errors mentioned below

**To Reproduce**
	
	◦	docker-compose up -d
	◦	docker-compose stop ibf-dashboard
	◦	cd interfaces/IBF-dashboard
	◦	npm start

**Expected behaviour**
All containers mentioned in the docker-compose file /IBF-system/docker-compose.yml be up and running.
Application should load and respond properly on the localhost:4200.

**Screenshots**
Attached below.

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser : chrome
 - Version : 92.*

**Workaround**
The containers ibf-system_ibf-pipeline , ibf-system_ibf-api-service do not start 

The container <ibf-pipeline > and <ibf-service> do not start automatically via the docker compose up command. The workaround for this would be, manually start the container <ibf-pipeline > and <ibf-service> and run this command.

- docker compose exec ibf-pipeline python3 runPipeline.py

These below commands come in handy when you face such issue:
1 docker-compose -f docker-compose.yml -f docker-compose.override.yml up
2 docker compose exec ibf-api-service bash
3 docker compose exec ibf-pipeline python3 runPipeline.py
4 docker-compose exec ibf-api-service npm run seed
5 docker-compose up -d ibf-api-service  
6 docker-compose logs -f ibf-api-service
7 docker-compose restart ibf-api-service
8 docker-compose exec ibf-api-service npm install

**Use them as and when needed**

![error-screenshot-01](https://user-images.githubusercontent.com/86838833/128673346-925b299c-feb7-4a0a-92fc-c61bf176aede.png)
![error-screenshot-2](https://user-images.githubusercontent.com/86838833/128673374-88f995fc-05ae-40cb-a411-d336e2ead84b.png)

**Comment by jannisvisser** [comment]
@SwatiTh I don't agree at all that this is a known/accepted issue.

The errors you mention here should not happen, and to be honest I don't think you can run the system correctly (which you are doing now) if these issues happen. Are you still expericieng these errors?

**Comment by jannisvisser** [comment]
I am closing this issue, because it has been solved by the new migration-setup.
